##
## EPITECH PROJECT, 2021
## B-FUN-300-COT-3-1-pushswapchecker-mohamed.salifou
## File description:
## Makefile
##

SRC	=	pushswap_checker.hs

$(NAME): $(SRC)
	@ghc $(SRC)

all:
	@ghc $(SRC)

clean:
	rm -f *.o
	rm -f *.hi
	rm -f *~

fclean:	clean
	rm -f pushswap_checker

re:	fclean all